name: pre-commit

on:
    workflow_call:
  
permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: "3.10"
    - run: echo "::add-matcher::.github/workflows/matchers/actionlint.json"
    - run: echo "::add-matcher::.github/workflows/matchers/mypy.json"
    - name: Checkout vllm-project/vllm repo
      uses: actions/checkout@v4
      with:
        repository: vllm-project/vllm
        path: vllm-empty
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      env:
        PYTHONPATH: ${{ github.workspace }}/vllm-empty:${{ env.PYTHONPATH }}
      with:
        extra_args: --all-files --hook-stage manual
